### PR TITLE
Assignment 1.4. Lifting State and Props Handling

### PR DESCRIPTION
**Pull request by AlonaVladymyrovaTrinity**
Move Todo List into State
 Open /src/App.js
 Create new state variable named todoList with setter setTodoList and default value of an empty Array
 Pass todoList state as a prop named todoList to the TodoList component
 Open /src/TodoList.js
 Add props as a parameter to the TodoList functional component
 Change todoList to reference props instead of the hard-coded variable
 Delete the hard-coded todoList variable
 Run your application and view in browser
 Verify that your Todo List is now empty (no list items)
Control "Add Todo" Input
 Open /src/AddTodoForm.js
 Create new state variable named todoTitle with setter setTodoTitle
 Modify the <input> element to be a controlled input
 Add value prop equal to todoTitle from component props
 Add onChange prop equal to handleTitleChange function reference (we will declare this function in the next step)
 Above the handleAddTodo function, declare a new function named handleTitleChange that takes event as a parameter....

### CODE REVIEW

**Review by leo-mutuku — COMMENTED** [review]
Lifting state and props handling correctly implemented.

Comment: Type safety.
- Type safety is the extend to which a programming language discourages or prevents type errors. Statically type languages have this feature built in e.g,java, C# ,typescript e.t.c
- JavaScript is not type safe which means runtime error errors might occur where the developer did catch or expected a different type.

To be researched further.
return <TodoListItem key={todo.id.toString()}
--
Implicit conversion of variable in JavaScript may throw an error at runtime when the expected type is not passed. In static typed, errors will be caught during development.
In the above, we know that id is of type integer and we convert it to string. If the passed id will be of type string JavaScript will still run perfect but at some case we may run into runtime errors. Take note of the datatype

**Comment by AlonaVladymyrovaTrinity** [comment]
> Lifting state and props handling correctly implemented.
> 
> Comment: Type safety.
> 
> * Type safety is the extend to which a programming language discourages or prevents type errors. Statically type languages have this feature built in e.g,java, C# ,typescript e.t.c
> * JavaScript is not type safe which means runtime error errors might occur where the developer did catch or expected a different type.
> 
> ## To be researched further.
> return <TodoListItem key={todo.id.toString()}
> Implicit conversion of variable in JavaScript may throw an error at runtime when the expected type is not passed. In static typed, errors will be caught during development. In the above, we know that id is of type integer and we convert it to string. If the passed id will be of type string JavaScript will still run perfect but at some case we may run into runtime errors. Take note of the datatype

I followed to the example in React Documentation https://reactjs.org/docs/lists-and-keys.html
Example:
```
function ListItem(props) {
  // Correct! There is no need to specify the key here:
  return <li>{props.value}</li>;
}

function NumberList(props) {
  const numbers = props.numbers;
  const listItems = numbers.map((number) =>
    // Correct! Key should be specified inside the array.
    <ListItem key={number.toString()} value={number} />
  );
  return (
    <ul>
      {listItems}
    </ul>
  );
}
```
And I asked you this question in one of previous form submissions. What is the best practices? Should I do that as React Documentation suggest? Or I it's better to just do something like this:
` <TodoListItem key={todo.id}`
What is the best practice and why?

**Comment by AlonaVladymyrovaTrinity** [comment]
I committed and pushed fix for this issue. Please verify.

**Review by leo-mutuku — COMMENTED** [review]
Great

**Review by leo-mutuku — APPROVED** [review]

**Pull request merged**
